---
- name: Include tasks for specific Linux release.
  ansible.builtin.include_tasks: "{{ ansible_system }}/{{ ansible_distribution_file_variety }}.yml"

- name: Include Network tasks.
  ansible.builtin.include_tasks: "{{ ansible_system }}/network.yml"

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Role dependencies.
  include_role:
    name: "ansible-role-linux-haproxy"
  vars:
    haproxy_keepalived_dept: true
    haproxy_keepalived_vip: "{{ rke2_server }}"
    haproxy_servers: "{{ rke2_servers }}"
    haproxy_proxy_args: "{{ rke2_haproxy_proxy_args }}"
  when:
    - rke2_haproxy_dept | bool
    - rke2_node_role == "server"

- name: Include configuration tasks.
  ansible.builtin.include_tasks: "{{ ansible_system }}/configuration.yml"

#- name: Check if already been initialized.
#  stat:
#    path: "/etc/rancher/rke2/rke2-pss.yaml"
#  register: rke2_init_stat

- name: Include Rancher Kubernetes Engine v2 tasks.
  ansible.builtin.include_tasks: "{{ ansible_system }}/rke2.yml"
#  when: not rke2_init_stat.stat.exists | bool
