---
- name: Include tasks for specific Linux release.
  ansible.builtin.include_tasks: "{{ ansible_system }}/{{ ansible_distribution_file_variety }}.yml"

- name: Include configuration tasks.
  ansible.builtin.include_tasks: "{{ ansible_system }}/configuration.yml"

- name: Include firewall tasks.
  ansible.builtin.include_tasks: "{{ ansible_system }}/network.yml"

- name: Include containerd tasks.
  ansible.builtin.include_tasks: "{{ ansible_system }}/containerd.yml"

- name: Force the handler to run immediately.
  meta: flush_handlers

- name: Check if already been initialized.
  stat:
    path: "/etc/rancher/rke2/rke2-pss.yaml"
  register: rke2_init_stat

- name: Include Rancher Kubernetes Engine v2 tasks.
  ansible.builtin.include_tasks: "{{ ansible_system }}/rke2.yml"
  when: not rke2_init_stat.stat.exists | bool
