# Common
debug: {{ rke2_debug | default(false) | bool }}
data-dir: "{{ rke2_data_dir }}/rke2"

# Cluster
token: '{{ lookup("password", "" + rke2_servers[0] + ":rke2 length=16 chars=ascii_letters,digits") }}'
server: "https://{% if rke2_server is defined %}{{ rke2_server }}{% else %}{{ rke2_servers[0] }}{% endif %}:9345"

# Components
{% if rke2_kubelet_arg is defined and rke2_kubelet_arg | length > 0 %}
kubelet-arg:
{% for item in rke2_kubelet_arg %}
  - "{{ item }}"
{% endfor %}
{% endif %}

# Security
profile: cis

# Node
node-label:
  - "environments={{ environments }}"
  - "datacenter={{ datacenter }}"
  - "domain={{ domain }}"
  - "customer={{ customer }}"
{% if rke2_node_extra_labels is defined and rke2_node_extra_labels | length > 0 %}
{% for item in rke2_node_extra_labels %}
  - "{{ item }}"
{% endfor %}
{% endif %}
protect-kernel-defaults: true
{% if ansible_selinux.status == "disabled" %}
selinux: false
{% else %}
selinux: true
{% endif %}