apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
allowedUnsafeSysctls: ["{{ rke2_kubelet_arg.unsafesysctls | list | join('","') }}"]
containerLogMaxFiles: {{ rke2_kubelet_arg.logmaxfiles | default(5) }}
containerLogMaxSize: "{{ rke2_kubelet_arg.logmaxsize | default('10Mi') }}"
failSwapOn: false
kubeAPIBurst: {{ rke2_kubelet_arg.kubeapiburst | default(100) }}
kubeAPIQPS: {{ rke2_kubelet_arg.kubeapiqps | default(50) }}
imageGCHighThresholdPercent: {{ rke2_kubelet_arg.imagegchighthresholdpercent | default(85) }}
imageGCLowThresholdPercent: {{ rke2_kubelet_arg.imagegclowthresholdpercent | default(80) }}
maxPods: {{ rke2_kubelet_arg.maxpods | default(110) }}
rotateCertificates: true
serializeImagePulls: {{ rke2_kubelet_arg.serializeimagepulls | bool | default(true) }}