---
- name: Gathering service facts.
  service_facts:
  register: services_state

- name: Transfer NetworkManager configuration file.
  copy:
    src: "rke2-canal.conf"
    dest: "/etc/NetworkManager/conf.d/rke2-canal.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Reloading the NetworkManager service.
  when:
    - services_state.ansible_facts.services["NetworkManager.service"] is defined
    - services_state.ansible_facts.services["NetworkManager.service"].state == 'running'

- name: Firewalld operation.
  block:
    - name: Allow Kubernetes control plane traffic.
      firewalld:
        port: "{{ item.port }}/{{ item.protocol }}"
        zone: "public"
        permanent: "yes"
        state: "enabled"
        immediate: "true"
      loop: "{{ rke2_server_network_rules_arg }}"
      when: rke2_node_role == "server"
    - name: Allow Kubernetes node traffic.
      firewalld:
        port: "{{ item.port }}/{{ item.protocol }}"
        zone: "public"
        permanent: "yes"
        state: "enabled"
        immediate: "true"
      loop: "{{ rke2_network_rules_arg }}"
  when:
    - services_state.ansible_facts.services["firewalld.service"] is defined
    - services_state.ansible_facts.services["firewalld.service"].state == 'running'
