---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution_file_variety }}.yml"

- name: Install the Kubernetes dependencies packages.
  package:
    name: "{{ item.name }}"
    state: "present"
    validate_certs: "no"
    disable_gpg_check: "yes"
  loop: "{{ rke2_packages }}"
  when: item.create | default(true) | bool
  register: rke2_dept_package_status
  until: rke2_dept_package_status is succeeded
  retries: 5
  delay: 2
